services:
  # MySQL 数据库
  ragforge-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ragforge123
      MYSQL_DATABASE: ragforge
      MYSQL_USER: ragforge
      MYSQL_PASSWORD: ragforge123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Elasticsearch 搜索引擎
  ragforge-elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  # MinIO 对象存储
  ragforge-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # Redis 缓存
  ragforge-redis:
    image: redis:7-alpine
    command: redis-server --requirepass ragforge123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  es_data:
  minio_data:
  redis_data:
