services:
  # RAGForge 主服务
  ragforge-ragforge:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9380:9380"
    environment:
      # 数据库配置
      - RAGFORGE_MYSQL_HOST=mysql
      - RAGFORGE_MYSQL_PORT=3306
      - RAGFORGE_MYSQL_USER=root
      - RAGFORGE_MYSQL_PASSWORD=ragforge123
      - RAGFORGE_MYSQL_DBNAME=ragforge
      
      # Elasticsearch 配置
      - RAGFORGE_ES_HOSTS=http://elasticsearch:9200
      - RAGFORGE_ES_USERNAME=elastic
      - RAGFORGE_ES_PASSWORD=
      
      # MinIO 配置
      - RAGFORGE_MINIO_HOST=minio:9000
      - RAGFORGE_MINIO_USER=minioadmin
      - RAGFORGE_MINIO_PASSWORD=minioadmin
      - RAGFORGE_MINIO_BUCKET_ENCRYPTION=false
      
      # Redis 配置
      - RAGFORGE_REDIS_HOST=redis
      - RAGFORGE_REDIS_PORT=6379
      - RAGFORGE_REDIS_PASSWORD=ragforge123
      
      # LLM 配置
      - RAGFORGE_LLM_FACTORY=OpenAI-API-Compatible
      - RAGFORGE_LLM_API_KEY=gpustack_9ee4961bc8fbe141_317180d1e53cb4eee68633d301adfd15
      - RAGFORGE_LLM_BASE_URL=http://101.52.216.178:890/v1
    depends_on:
      - ragforge-mysql
      - ragforge-elasticsearch
      - ragforge-minio
      - ragforge-redis
    restart: unless-stopped
    volumes:
      - ragforge_logs:/ragforge/logs
      - ragforge_data:/root/.ragforge

  # Web 控制台 - 生产环境
  ragforge-web:
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - RAGFORGE_BACKEND_API_URL=http://ragforge-ragforge:9380
    depends_on:
      - ragforge-ragforge
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web 控制台 - 开发环境（可选）
  ragforge-web-dev:
    build:
      context: ../web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - RAGFORGE_BACKEND_API_URL=http://ragforge-ragforge:9380
      - PORT=3000
    depends_on:
      - ragforge-ragforge
    profiles:
      - dev

  # MySQL 数据库
  ragforge-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ragforge123
      MYSQL_DATABASE: ragforge
      MYSQL_USER: ragforge
      MYSQL_PASSWORD: ragforge123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Elasticsearch 搜索引擎
  ragforge-elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  # MinIO 对象存储
  ragforge-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # Redis 缓存
  ragforge-redis:
    image: redis:7-alpine
    command: redis-server --requirepass ragforge123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  es_data:
  minio_data:
  redis_data:
  ragforge_logs:
  ragforge_data:
